variable "DOCDB_ENGINE" {}
variable "DOCDB_ENGINE_VERSION" {}
variable "DOCDB_INSTANCE_CLASS" {}
variable "PRIVATE_SUBNET_ID" {}
variable "DOCDB_PORT" {}
variable "ALLOW_SG_CIDR" {}
variable "DOCDB_PG_FAMILY" {}
variable "PROJECT" {}
variable "ENV" {}
variable "VPC_ID" {}